apiVersion: v2
name: adot-exporter-for-eks-on-ec2
description: A Helm chart for collecting metrics using ADOT Collector to send to AWS monitoring services.
type: application
version: 0.13.0
appVersion: "0.27.0"
kubeVersion: ">=1.19.0-0"
maintainers:
  - name: Bryan Aguilar
    email: bryaag@amazon.com
home: https://github.com/aws-observability/aws-otel-helm-charts/adot-exporter-for-eks-on-ec2
sources:
  - https://github.com/aws-observability/aws-otel-helm-charts/adot-exporter-for-eks-on-ec2
